import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import ApolloWrapper from "../components/ApolloWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          <Navbar />
          {children}
        </ApolloWrapper>
      </body>
    </html>
  );
}

// import React from "react";
// import * as ReactDOM from "react-dom/client";
// import { ApolloClient, InMemoryCache, ApolloProvider } from "@apollo/client";
// import App from "./App";
// import RootLayout from "./layout";

// const client = new ApolloClient({
//   uri: "https://current--anilist-graph-2024.apollographos.net/graphql",
//   cache: new InMemoryCache(),
// });

// // Supported in React 18+
// const root = ReactDOM.createRoot(document.getElementById("root"));

// root.render(
//   <ApolloProvider client={client}>
//     <RootLayout>
//       <App />
//     </RootLayout>
//   </ApolloProvider>
// );
